### PR TITLE
Added ts files to package_data

### PR DESCRIPTION
**Pull request by philippjfr**
- [x] Fixes https://github.com/pyviz/EarthSim/issues/146

### CODE REVIEW

**Comment by ceball** [comment]
I would mildly prefer not to use package_data like this. For instance, I believe that although this change will result in the files you've specified being installed via something like python setup.py install from the github source, it won't result in them being included in an sdist. (Which will be confusing in the future.)

In a previous PR, I removed all packaging related code from the PR at the suggestion of a review, because that code is unused - i.e. we are currently only using a develop install with dependencies installed via conda from an explicit list, pinned to certain channels. (And I agreed with that review.)

However, if we need to support other ways right now, I would be up for adding back some of that packaging code in a new PR - but I would still prefer not to use package_data like this, though :)

**Comment by philippjfr** [comment]
Ugh, missed your comment by a few seconds. Do you want me to revert?

**Comment by jbednar** [comment]
Depends what the proposed alternative solution is?

**Comment by ceball** [comment]
Heh, my screen went all funny because I think we clicked at the same time :)

**Comment by ceball** [comment]
> Depends what the proposed alternative solution is?

Do you want to/do we need to support anything other than a develop install at the moment?

If so, my preference would be a rule in MANIFEST.in and include_package_data=True. That way, you declare one or more rules about what files should go into a package (e.g. an sdist), which in combination with include_package_data ensures the same files get installed.

Rules in manifest.in can be broad or narrow. There are also probably plugins to use files from e.g. git.

**Pull request merged**
