### PR TITLE
Add GrabCut code and demo

### PR DESCRIPTION
**Pull request by philippjfr**
Adds code for GrabCut example along with a Topics notebook showing it in use. Currently also adds the data directly to the repo, if we don't want to store it inside the repo it will have to be uploaded somewhere persistent, e.g. the datashader S3 bucket.

### CODE REVIEW

**Comment by jbednar** [comment]
image

How hard would it be to add a lasso tool to select the random lakes, etc. and delete them from the countour (i.e. manual cleanup)?

**Comment by philippjfr** [comment]
>How hard would it be to add a lasso tool to select the random lakes, etc. and delete them from the countour (i.e. manual cleanup)?

Not straightforward and very inefficient since the nan separated paths would have to be split into actually distinct paths to apply the selection. I think an automatic approach for eliminating small paths is a higher priority and what their current workflow uses.

**Comment by jbednar** [comment]
I guess this can wait until we get a ragged array type into Pandas, at which point it should be simple to toggle a visibility flag for each segment?

**Comment by kcpevey** [comment]
Looks good! I'll open an issue for some direction on the next steps and commentary.

**Pull request merged**
