### PR TITLE
Add a GrabCut dashboard

### PR DESCRIPTION
**Pull request by philippjfr**
Uses a new panel based approach to step through multi-panel workflows. Next/Previous buttons can be used to flip between region selection and the grabcut panel with a spinner as you're waiting in between.

screen shot 2018-10-17 at 7 25 19 pm

screen shot 2018-10-17 at 7 25 27 pm

screen shot 2018-10-17 at 7 26 54 pm

### CODE REVIEW

**Comment by kcpevey** [comment]
A spinner?!?!?! Nice!!

**Comment by kcpevey** [comment]
I was going to ask about next/previous tomorrow... well done!

**Comment by philippjfr** [comment]
>A spinner?!?!?! Nice!!

It's a bit of a cheat as it's just a spinning gif. It also only display while you're transitioning between the region selection and the grabcut panels but not when you press the "Update contour" button.

**Comment by philippjfr** [comment]
So I'm currently blocked from merging this because the GSSHA workflow is making queries to http://prj2epsg.org/search which appears to be down this morning.

**Comment by philippjfr** [comment]
@kcpevey Finally ready to merge this, make sure to update to the latest releases before updating.

**Pull request merged**
