### PR TITLE
Added machinery to compile custom models

### PR DESCRIPTION
**Pull request by philippjfr**
Use new machinery in bokeh to ship precompiled bokeh models to avoid recompiling on every import.

@kcpevey The next time you pull after this PR has been merged make sure to run ``pip install -e`` or ``python setup.py develop`` in the earthsim root folder. This will compile the custom bokeh models speeding up future imports.

### CODE REVIEW

**Comment by kcpevey** [comment]
@philippjfr This explains why hv/gv and others require me to rerun `python setup.py develop` while some packages (Earthsim before now, I think) only required a `git pull` to update.

**Comment by philippjfr** [comment]
>This explains why hv/gv and others require me to rerun python setup.py develop while some packages (Earthsim before now, I think) only required a git pull to update.

It does not, neither should require that since neither ship with custom models.

**Comment by kcpevey** [comment]
> neither should require that since neither ship with custom models.

Hmmm. Strange. I'll have to pay closer attention to things to figure out what was happening. NBD.

**Comment by philippjfr** [comment]
Let us know if you figure it out.

**Pull request merged**
