### PR TITLE
Not for merging: debugging environment

### PR DESCRIPTION
**Pull request by ceball**
Debugging env: added erdc quest package, and removed its dependencies from env (except where they are also direct dependencies of earthsim module/notebooks).

### CODE REVIEW

**Comment by ceball** [comment]
@philippjfr, just wondering if you happen to know immediately what might be causing the test failure at https://travis-ci.org/pyviz/EarthSim/jobs/382253594#L1865 ? I've removed some dependencies from the environment.yaml (see diff); specifically, I've removed dependencies that aren't direct dependencies of earthsim (module or notebooks) but which are dependencies of quest.

For reference, the quest conda package has the following dependencies:

```
        - click
        - distributed
        - fiona
        - gdal
        - geojson
        - geopandas
        - girder-client
        - hs_restclient
        - jinja2
        - numpy
        - param
        - peewee
        - pint
        - pony
        - psutil
        - pytest-cov
        - pyyaml
        - rasterio
        - sortedcollections
        - sphinx
        - sphinx_rtd_theme
        - stevedore
        - tornado
        - ulmo
        - werkzeug
```

**Comment by ceball** [comment]
In case the link doesn't work well, it's

```
An error occurred while executing the following cell:
E                   ------------------
E                   %%opts Shape [width=600 height=400] (alpha=0.5)
E                   from earthsim.io import save_shapefile
E                   if vertex_stream.data:
E                       edited_shape_fname = '../data/vicksburg_watershed_edited/watershed_boundary.shp'
E                       dir_name = os.path.dirname(edited_shape_fname)
E                       if not os.path.isdir(dir_name): os.makedirs(dir_name)
E                       save_shapefile(vertex_stream.data, edited_shape_fname, shapefile)
E                       mask_shape = gv.Shape.from_shapefile(edited_shape_fname)
E                   mask_shape = mask_shape.opts() # Clear options to avoid adding edit tool
E                   mask_shape.last.clone(crs=ccrs.GOOGLE_MERCATOR)
E                   ------------------
E                   
E                   ---------------------------------------------------------------------------
E                   TypeError                                 Traceback (most recent call last)
E                   <ipython-input-7-854d140aebe2> in <module>()
E                         5     if not os.path.isdir(dir_name): os.makedirs(dir_name)
E                         6     save_shapefile(vertex_stream.data, edited_shape_fname, shapefile)
E                   ----> 7     mask_shape = gv.Shape.from_shapefile(edited_shape_fname)
E                         8 mask_shape = mask_shape.opts() # Clear options to avoid adding edit tool
E                         9 mask_shape.last.clone(crs=ccrs.GOOGLE_MERCATOR)
E                   
E                   ~/miniconda/envs/earthsim/lib/python3.6/site-packages/geoviews/element/geo.py in from_shapefile(cls, shapefile, *args, **kwargs)
E                       524         """
E                       525         reader = Reader(shapefile)
E                   --> 526         return cls.from_records(reader.records(), *args, **kwargs)
E                       527 
E                       528 
E                   
E                   ~/miniconda/envs/earthsim/lib/python3.6/site-packages/geoviews/element/geo.py in from_records(cls, records, dataset, on, value, index, drop_missing, **kwargs)
E                       615             else:
E                       616                 key = (i,)
E                   --> 617             data.append((key, Shape(rec.geometry, **kwargs)))
E                       618         if notfound:
E                       619             kdims = ['Index']+kdims
E                   
E                   ~/miniconda/envs/earthsim/lib/python3.6/site-packages/geoviews/element/geo.py in __init__(self, data, kdims, vdims, **params)
E                       512         if not isinstance(data, BaseGeometry):
E                       513             raise TypeError('%s data has to be a shapely geometry type.'
E                   --> 514                             % type(data).__name__)
E                       515         super(Shape, self).__init__(data, kdims=kdims, vdims=vdims, **params)
E                       516 
E                   
E                   TypeError: NoneType data has to be a shapely geometry type.
```

**Comment by philippjfr** [comment]
Note that when I run the notebook locally I have no issues whatsoever.

**Comment by ceball** [comment]
Thanks, I just came back to post my conclusion that it's not down to the changes here :)

If you can't reproduce it on mac, feel free to make an issue and assign it to me, and I'll check it out.

(I have a possibly similar-ish issue to debug for datashader too. Similar-ish in that it's a problem which mysteriously only seems to happen on linux, and involves the word 'shape' ;) "CB got ShapefileException: Unable to open ../data/cb_2015_us_cd114_5m.dbf or ../data/cb_2015_us_cd114_5m.shp when running examples on linux (but file's hash matched JAB's)." from https://github.com/bokeh/datashader/issues/594)

**Comment by philippjfr** [comment]
Thanks, it would indeed be helpful to know if you encounter an error when running through DrawingTools on linux.

**Comment by ceball** [comment]
What about other errors on travis, e.g. on examples/user_guide/Specifying_Meshes.ipynb - does that one also run fine locally for you on mac?

https://travis-ci.org/pyviz/EarthSim/builds/382221733#L2197

```
An error occurred while executing the following cell:
E                   ------------------
E                   %%opts Polygons (color='red' alpha=0.5 selection_alpha=0.8 nonselection_alpha=0.2) Layout [shared_datasource=True]
E                   %%opts Points (size=10 nonselection_alpha=0.5)
E                   annot = PolyAndPointAnnotator()
E                   dashboard = FiligreeMeshDashboard(draw_helper=annot)
E                   dashboard.mesh.create_constant_size_function(500, 5)
E                   dashboard.mesh.set_outside_mesh_size(500)
E                   parambokeh.Widgets(dashboard)
E                   dashboard.view()
E                   ------------------
E                   
E                   ---------------------------------------------------------------------------
E                   IndexError                                Traceback (most recent call last)
E                   ~/miniconda/envs/earthsim/lib/python3.6/site-packages/IPython/core/formatters.py in __call__(self, obj, include, exclude)
E                       968 
E                       969             if method is not None:
E                   --> 970                 return method(include=include, exclude=exclude)
E                       971             return None
E                       972         else:
E                   
E                   ~/miniconda/envs/earthsim/lib/python3.6/site-packages/holoviews/core/dimension.py in _repr_mimebundle_(self, include, exclude)
E                      1229         combined and returned.
E                      1230         """
E                   -> 1231         return Store.render(self)
E                      1232 
E                      1233 
E                   
E                   ~/miniconda/envs/earthsim/lib/python3.6/site-packages/holoviews/core/options.py in render(cls, obj)
E                      1287         data, metadata = {}, {}
E                      1288         for hook in hooks:
E                   -> 1289             ret = hook(obj)
E                      1290             if ret is None:
E                      1291                 continue
E                   
E                   ~/miniconda/envs/earthsim/lib/python3.6/site-packages/holoviews/ipython/display_hooks.py in pprint_display(obj)
E                       278     if not ip.display_formatter.formatters['text/plain'].pprint:
E                       279         return None
E                   --> 280     return display(obj, raw_output=True)
E                       281 
E                       282 
E                   
E                   ~/miniconda/envs/earthsim/lib/python3.6/site-packages/holoviews/ipython/display_hooks.py in display(obj, raw_output, **kwargs)
E                       251     elif isinstance(obj, (Layout, NdLayout, AdjointLayout)):
E                       252         with option_state(obj):
E                   --> 253             output = layout_display(obj)
E                       254     elif isinstance(obj, (HoloMap, DynamicMap)):
E                       255         with option_state(obj):
E                   
E                   ~/miniconda/envs/earthsim/lib/python3.6/site-packages/holoviews/ipython/display_hooks.py in wrapped(element)
E                       140         try:
E                       141             max_frames = OutputSettings.options['max_frames']
E                   --> 142             mimebundle = fn(element, max_frames=max_frames)
E                       143             if mimebundle is None:
E                       144                 return {}, {}
E                   
E                   ~/miniconda/envs/earthsim/lib/python3.6/site-packages/holoviews/ipython/display_hooks.py in layout_display(layout, max_frames)
E                       221         return None
E                       222 
E                   --> 223     return render(layout)
E                       224 
E                       225 
E                   
E                   ~/miniconda/envs/earthsim/lib/python3.6/site-packages/holoviews/ipython/display_hooks.py in render(obj, **kwargs)
E                        63         renderer = renderer.instance(fig='png')
E                        64 
E                   ---> 65     return renderer.components(obj, **kwargs)
E                        66 
E                        67 
E                   
E                   ~/miniconda/envs/earthsim/lib/python3.6/site-packages/holoviews/plotting/bokeh/renderer.py in components(self, obj, fmt, comm, **kwargs)
E                       257         # Bokeh has to handle comms directly in <0.12.15
E                       258         comm = False if bokeh_version < '0.12.15' else comm
E                   --> 259         return super(BokehRenderer, self).components(obj,fmt, comm, **kwargs)
E                       260 
E                       261 
E                   
E                   ~/miniconda/envs/earthsim/lib/python3.6/site-packages/holoviews/plotting/renderer.py in components(self, obj, fmt, comm, **kwargs)
E                       319             plot = obj
E                       320         else:
E                   --> 321             plot, fmt = self._validate(obj, fmt)
E                       322 
E                       323         widget_id = None
E                   
E                   ~/miniconda/envs/earthsim/lib/python3.6/site-packages/holoviews/plotting/renderer.py in _validate(self, obj, fmt, **kwargs)
E                       218         if isinstance(obj, tuple(self.widgets.values())):
E                       219             return obj, 'html'
E                   --> 220         plot = self.get_plot(obj, renderer=self, **kwargs)
E                       221 
E                       222         fig_formats = self.mode_formats['fig'][self.mode]
E                   
E                   ~/miniconda/envs/earthsim/lib/python3.6/site-packages/holoviews/plotting/bokeh/renderer.py in get_plot(self_or_cls, obj, doc, renderer)
E                       150             doc = Document() if self_or_cls.notebook_context else curdoc()
E                       151         doc.theme = self_or_cls.theme
E                   --> 152         plot = super(BokehRenderer, self_or_cls).get_plot(obj, renderer)
E                       153         plot.document = doc
E                       154         return plot
E                   
E                   ~/miniconda/envs/earthsim/lib/python3.6/site-packages/holoviews/plotting/renderer.py in get_plot(self_or_cls, obj, renderer)
E                       205             init_key = tuple(v if d is None else d for v, d in
E                       206                              zip(plot.keys[0], defaults))
E                   --> 207             plot.update(init_key)
E                       208         else:
E                       209             plot = obj
E                   
E                   ~/miniconda/envs/earthsim/lib/python3.6/site-packages/holoviews/plotting/plot.py in update(self, key)
E                       511     def update(self, key):
E                       512         if len(self) == 1 and ((key == 0) or (key == self.keys[0])) and not self.drawn:
E                   --> 513             return self.initialize_plot()
E                       514         item = self.__getitem__(key)
E                       515         self.traverse(lambda x: setattr(x, '_updated', True))
E                   
E                   ~/miniconda/envs/earthsim/lib/python3.6/site-packages/holoviews/plotting/bokeh/plot.py in initialize_plot(self, plots, ranges)
E                       796             if subplot is not None:
E                       797                 shared_plots = passed_plots if self.shared_axes else None
E                   --> 798                 subplots = subplot.initialize_plot(ranges=ranges, plots=shared_plots)
E                       799 
E                       800                 # Computes plotting offsets depending on
E                   
E                   ~/miniconda/envs/earthsim/lib/python3.6/site-packages/holoviews/plotting/bokeh/plot.py in initialize_plot(self, ranges, plots)
E                       929             if subplot:
E                       930                 passed_plots = plots  + adjoined_plots
E                   --> 931                 adjoined_plots.append(subplot.initialize_plot(ranges=ranges, plots=passed_plots))
E                       932             else:
E                       933                 adjoined_plots.append(empty_plot(0, 0))
E                   
E                   ~/miniconda/envs/earthsim/lib/python3.6/site-packages/geoviews/plotting/bokeh/plot.py in initialize_plot(self, ranges, plot, plots, source)
E                        82     def initialize_plot(self, ranges=None, plot=None, plots=None, source=None):
E                        83         opts = {} if isinstance(self, HvOverlayPlot) else {'source': source}
E                   ---> 84         fig = super(GeoPlot, self).initialize_plot(ranges, plot, plots, **opts)
E                        85         if self.geographic and self.show_bounds and not self.overlaid:
E                        86             from . import GeoShapePlot
E                   
E                   ~/miniconda/envs/earthsim/lib/python3.6/site-packages/holoviews/plotting/bokeh/element.py in initialize_plot(self, ranges, plot, plots)
E                      1389             frame = None
E                      1390             if self.tabs: subplot.overlaid = False
E                   -> 1391             child = subplot.initialize_plot(ranges, plot, plots)
E                      1392             if isinstance(element, CompositeOverlay):
E                      1393                 frame = element.get(key, None)
E                   
E                   ~/miniconda/envs/earthsim/lib/python3.6/site-packages/geoviews/plotting/bokeh/plot.py in initialize_plot(self, ranges, plot, plots, source)
E                        82     def initialize_plot(self, ranges=None, plot=None, plots=None, source=None):
E                        83         opts = {} if isinstance(self, HvOverlayPlot) else {'source': source}
E                   ---> 84         fig = super(GeoPlot, self).initialize_plot(ranges, plot, plots, **opts)
E                        85         if self.geographic and self.show_bounds and not self.overlaid:
E                        86             from . import GeoShapePlot
E                   
E                   ~/miniconda/envs/earthsim/lib/python3.6/site-packages/holoviews/plotting/bokeh/element.py in initialize_plot(self, ranges, plot, plots, source)
E                       726         self.handles['plot'] = plot
E                       727 
E                   --> 728         self._init_glyphs(plot, element, ranges, source)
E                       729         if not self.overlaid:
E                       730             self._update_plot(key, plot, style_element)
E                   
E                   ~/miniconda/envs/earthsim/lib/python3.6/site-packages/holoviews/plotting/bokeh/element.py in _init_glyphs(self, plot, element, ranges, source)
E                       677         else:
E                       678             style = self.style[self.cyclic_index]
E                   --> 679             data, mapping, style = self.get_data(element, ranges, style)
E                       680             current_id = element._plot_id
E                       681         if source is None:
E                   
E                   ~/miniconda/envs/earthsim/lib/python3.6/site-packages/geoviews/plotting/bokeh/plot.py in get_data(self, element, ranges, style)
E                       150         if self._project_operation and self.geographic:
E                       151             element = self._project_operation(element, projection=proj)
E                   --> 152         return super(GeoPlot, self).get_data(element, ranges, style)
E                       153 
E                       154 
E                   
E                   ~/miniconda/envs/earthsim/lib/python3.6/site-packages/holoviews/plotting/bokeh/path.py in get_data(self, element, ranges, style)
E                       144 
E                       145     def get_data(self, element, ranges, style):
E                   --> 146         paths = element.split(datatype='array', dimensions=element.kdims)
E                       147         if self.static_source:
E                       148             data = dict()
E                   
E                   ~/miniconda/envs/earthsim/lib/python3.6/site-packages/holoviews/element/path.py in split(self, start, end, datatype, **kwargs)
E                       118                 raise ValueError("%s datatype not support" % datatype)
E                       119             return [obj]
E                   --> 120         return self.interface.split(self, start, end, datatype, **kwargs)
E                       121 
E                       122 
E                   
E                   ~/miniconda/envs/earthsim/lib/python3.6/site-packages/geoviews/data/geopandas.py in split(cls, dataset, start, end, datatype, **kwargs)
E                       152         objs = []
E                       153         xdim, ydim = dataset.kdims[:2]
E                   --> 154         row = dataset.data.iloc[0]
E                       155         arr = geom_to_array(row['geometry'])
E                       156         d = {(xdim.name, ydim.name): arr}
E                   
E                   ~/miniconda/envs/earthsim/lib/python3.6/site-packages/pandas/core/indexing.py in __getitem__(self, key)
E                      1476 
E                      1477             maybe_callable = com._apply_if_callable(key, self.obj)
E                   -> 1478             return self._getitem_axis(maybe_callable, axis=axis)
E                      1479 
E                      1480     def _is_scalar_access(self, key):
E                   
E                   ~/miniconda/envs/earthsim/lib/python3.6/site-packages/pandas/core/indexing.py in _getitem_axis(self, key, axis)
E                      2100 
E                      2101             # validate the location
E                   -> 2102             self._validate_integer(key, axis)
E                      2103 
E                      2104             return self._get_loc(key, axis=axis)
E                   
E                   ~/miniconda/envs/earthsim/lib/python3.6/site-packages/pandas/core/indexing.py in _validate_integer(self, key, axis)
E                      2007         l = len(ax)
E                      2008         if key >= l or key < -l:
E                   -> 2009             raise IndexError("single positional indexer is out-of-bounds")
E                      2010 
E                      2011     def _getitem_tuple(self, tup):
E                   
E                   IndexError: single positional indexer is out-of-bounds
E                   IndexError: single positional indexer is out-of-bounds
../../../miniconda/envs/earthsim/lib/python3.6/site-packages/nbconvert/preprocessors/execute.py:286: CellExecutionError
----------------------------- Captured stderr call -----------------------------
filigree: /home/travis/miniconda/envs/earthsim/bin/../lib/libstdc++.so.6: version `GLIBCXX_3.4.20' not found (required by filigree)
filigree: /home/travis/miniconda/envs/earthsim/bin/../lib/libstdc++.so.6: version `GLIBCXX_3.4.21' not found (required by filigree)
filigree: /home/travis/miniconda/envs/earthsim/bin/../lib/libstdc++.so.6: version `CXXABI_1.3.9' not found (required by /home/travis/miniconda/envs/earthsim/bin/../lib/libboost_thread.so.1.65.1)
filigree: /home/travis/miniconda/envs/earthsim/bin/../lib/libstdc++.so.6: version `GLIBCXX_3.4.21' not found (required by /home/travis/miniconda/envs/earthsim/bin/../lib/libboost_thread.so.1.65.1)
filigree: /home/travis/miniconda/envs/earthsim/bin/../lib/libstdc++.so.6: version `CXXABI_1.3.8' not found (required by /home/travis/miniconda/envs/earthsim/bin/../lib/libboost_filesystem.so.1.65.1)
filigree: /home/travis/miniconda/envs/earthsim/bin/../lib/libstdc++.so.6: version `CXXABI_1.3.9' not found (required by /home/travis/miniconda/envs/earthsim/bin/../lib/libboost_filesystem.so.1.65.1)
filigree: /home/travis/miniconda/envs/earthsim/bin/../lib/libstdc++.so.6: version `GLIBCXX_3.4.20' not found (required by /home/travis/miniconda/envs/earthsim/bin/../lib/libboost_filesystem.so.1.65.1)
filigree: /home/travis/miniconda/envs/earthsim/bin/../lib/libstdc++.so.6: version `GLIBCXX_3.4.21' not found (required by /home/travis/miniconda/envs/earthsim/bin/../lib/libboost_filesystem.so.1.65.1)
filigree: /home/travis/miniconda/envs/earthsim/bin/../lib/libstdc++.so.6: version `CXXABI_1.3.9' not found (required by /home/travis/miniconda/envs/earthsim/bin/../lib/libboost_system.so.1.65.1)
filigree: /home/travis/miniconda/envs/earthsim/bin/../lib/libstdc++.so.6: version `GLIBCXX_3.4.21' not found (required by /home/travis/miniconda/envs/earthsim/bin/../lib/libboost_system.so.1.65.1)
filigree: /home/travis/miniconda/envs/earthsim/bin/../lib/libstdc++.so.6: version `GLIBCXX_3.4.20' not found (required by /home/travis/miniconda/envs/earthsim/bin/../lib/libboost_log.so.1.65.1)
filigree: /home/travis/miniconda/envs/earthsim/bin/../lib/libstdc++.so.6: version `CXXABI_1.3.9' not found (required by /home/travis/miniconda/envs/earthsim/bin/../lib/libboost_log.so.1.65.1)
filigree: /home/travis/miniconda/envs/earthsim/bin/../lib/libstdc++.so.6: version `GLIBCXX_3.4.21' not found (required by /home/travis/miniconda/envs/earthsim/bin/../lib/libboost_log.so.1.65.1)
filigree: /home/travis/miniconda/envs/earthsim/bin/../lib/libstdc++.so.6: version `CXXABI_1.3.9' not found (required by /home/travis/miniconda/envs/earthsim/bin/../lib/libboost_timer.so.1.65.1)
filigree: /home/travis/miniconda/envs/earthsim/bin/../lib/libstdc++.so.6: version `GLIBCXX_3.4.21' not found (required by /home/travis/miniconda/envs/earthsim/bin/../lib/libboost_timer.so.1.65.1)
filigree: /home/travis/miniconda/envs/earthsim/bin/../lib/libstdc++.so.6: version `CXXABI_1.3.9' not found (required by /home/travis/miniconda/envs/earthsim/bin/../lib/libboost_serialization.so.1.65.1)
filigree: /home/travis/miniconda/envs/earthsim/bin/../lib/libstdc++.so.6: version `GLIBCXX_3.4.21' not found (required by /home/travis/miniconda/envs/earthsim/bin/../lib/libboost_serialization.so.1.65.1)
filigree: /home/travis/miniconda/envs/earthsim/bin/../lib/libstdc++.so.6: version `GLIBCXX_3.4.20' not found (required by /home/travis/miniconda/envs/earthsim/bin/../lib/libboost_log_setup.so.1.65.1)
filigree: /home/travis/miniconda/envs/earthsim/bin/../lib/libstdc++.so.6: version `CXXABI_1.3.9' not found (required by /home/travis/miniconda/envs/earthsim/bin/../lib/libboost_log_setup.so.1.65.1)
filigree: /home/travis/miniconda/envs/earthsim/bin/../lib/libstdc++.so.6: version `GLIBCXX_3.4.21' not found (required by /home/travis/miniconda/envs/earthsim/bin/../lib/libboost_log_setup.so.1.65.1)
filigree: /home/travis/miniconda/envs/earthsim/bin/../lib/libstdc++.so.6: version `GLIBCXX_3.4.20' not found (required by /home/travis/miniconda/envs/earthsim/bin/../lib/libboost_regex.so.1.65.1)
filigree: /home/travis/miniconda/envs/earthsim/bin/../lib/libstdc++.so.6: version `CXXABI_1.3.8' not found (required by /home/travis/miniconda/envs/earthsim/bin/../lib/libboost_regex.so.1.65.1)
filigree: /home/travis/miniconda/envs/earthsim/bin/../lib/libstdc++.so.6: version `CXXABI_1.3.9' not found (required by /home/travis/miniconda/envs/earthsim/bin/../lib/libboost_regex.so.1.65.1)
filigree: /home/travis/miniconda/envs/earthsim/bin/../lib/libstdc++.so.6: version `GLIBCXX_3.4.21' not found (required by /home/travis/miniconda/envs/earthsim/bin/../lib/libboost_regex.so.1.65.1)
filigree: /home/travis/miniconda/envs/earthsim/bin/../lib/libstdc++.so.6: version `CXXABI_1.3.9' not found (required by /home/travis/miniconda/envs/earthsim/bin/../lib/./libboost_chrono.so.1.65.1)
filigree: /home/travis/miniconda/envs/earthsim/bin/../lib/libstdc++.so.6: version `GLIBCXX_3.4.21' not found (required by /home/travis/miniconda/envs/earthsim/bin/../lib/./libboost_chrono.so.1.65.1)
filigree: /home/travis/miniconda/envs/earthsim/bin/../lib/libstdc++.so.6: version `GLIBCXX_3.4.21' not found (required by /home/travis/miniconda/envs/earthsim/bin/../lib/./libboost_date_time.so.1.65.1)
filigree: /home/travis/miniconda/envs/earthsim/bin/../lib/libstdc++.so.6: version `CXXABI_1.3.9' not found (required by /home/travis/miniconda/envs/earthsim/bin/../lib/./libboost_date_time.so.1.65.1)
```

**Comment by ceball** [comment]
@philippjfr, I will close this PR as it's served its purpose for the particular debugging I was trying to do. However, it would be helpful for me to know which of the notebooks do and do not run ok for you locally (e.g. does user_guide/Specifying_Meshes.ipynb work for you locally?), along with your environment (packages, channels) and which git branch you're using. Thanks

**Comment by ceball** [comment]
> it would indeed be helpful to know if you encounter an error when running through DrawingTools on linux

@philippjfr, yes, I appear to have the same problems as travis. 

On master (with env created just now), problem with Drawing_Tools notebook (same as travis; shown in comment above: https://github.com/pyviz/EarthSim/pull/95#issuecomment-391069029).

On simplify_poly_annotator (with env created just now), problem with Drawing_Tools notebook (same problem as master), and problem with Specifying_Meshes (same as travis; shown in comment above: https://github.com/pyviz/EarthSim/pull/95#issuecomment-391152817).

What about this approach?
  1. confirm that all (non skipped) notebooks run ok for you in your current env (and preserve it)
  2. confirm that those notebooks still run ok for you in a fresh env/after updating your env (if you haven't already updated it recently)
  3. finish your PR, and merge it (if all notebooks did still run for you locally)
  4. record your env somewhere I can see it for reference, just in case
  5. I debug locally on linux

The reason I suggest that order is that (a) I'd rather tackle the env problem(s) on linux without too many moving bits and (b) presumably you and everyone else can continue with work on mac for now without being held up by not merging things because the tests are failing on linux...but if you have a better idea, let me know.

**Comment by philippjfr** [comment]
Okay it looks like I had an old version of geoviews installed (which wouldn't uninstall with conda for some reason). I'll try to fix it and get a new geoviews alpha release out asap.

**Pull request closed without merging**
