### PR TITLE
Enabled/added new tool features to existing examples

### PR DESCRIPTION
**Pull request by philippjfr**
* Switches the GrabCut notebook to use the FreehandDraw tool
* Enables vertex showing/snapping on PolyDraw tool

### CODE REVIEW

**Comment by jlstevens** [comment]
I'll integrate this change into the dashboard work as soon as it is ready.

**Comment by philippjfr** [comment]
>I'll integrate this change into the dashboard work as soon as it is ready.

We are currently installing everything from dev packages, which means that ideally we would release a HoloViews 1.11dev release.

**Comment by philippjfr** [comment]
That dev release would also need to relax the bokeh version requirement to allow 1.0 builds.

**Comment by jlstevens** [comment]
I agree we will need to cut a dev release soon.

**Comment by jlstevens** [comment]
The ``v1.11.0a2`` release is now available on the [pyviz channel](https://anaconda.org/pyviz/holoviews/files).

**Comment by philippjfr** [comment]
I'll merge. Further doc updates coming in another PR.

**Pull request merged**
