### PR TITLE
Fullpass

### PR DESCRIPTION
**Pull request by jbednar**
I've completed a pass over all the example notebooks, and had some questions:

For Specifying_Meshes:
1. I can't seem to get any reliable effect from adding points that have associated values like 100, 1000, or 1000.  Is it broken somehow?

For GSSHA_Workflow:
1. What happens when no bounding box and point is drawn?
2. What effect does having no elevation grid path have?
3. Does 'INFO:rasterio._base:Failed to auto identify EPSG: 7' indicate anything important?
4. What needs to happen for '# TODO: needs an update from Philipp'?
5. Does something need to happen for `db_session(Optional[database session]): Active database session object. Required for existing model.` and `project_manager(Optional[ProjectFile]): Initialized ProjectFile object. Required for existing model.`?
6. Should we update bokeh, or downgrade numpy, to get rid of `.../bokeh/core/json_encoder.py:80: FutureWarning: Conversion of the second argument of issubdtype from `float` to `np.floating` is deprecated.`?
7. Do we need to do anything about `# TODO: how does the info here relate to that set earlier?`?
8. Which packages are not open source? (Quest?)

For GSSHA_Parameter_Sweep:
1. It looks like there are three intensities simulated (128, 256, 512), yet the final visualization shows only two (256,512). What happened to 128?

Also, in the last commit here I turned off the bit that aborts when the simulation output directory exists, as it's very confusing and awkward to have to manually find and delete the output each time for the run to succeed when working on the notebook.  It seems to work fine, but it's worth double-checking that it's ok.  If not we could presumably put a datestamp in front of the output directory so that it will be unique each time.

### CODE REVIEW

**Comment by philippjfr** [comment]
>I can't seem to get any reliable effect from adding points that have assocated values like 100, 1000, or 1000. Is it broken somehow?

Cannot reproduce, worked fine on my first try and every subsequent edit I made.

>What happens when no bounding box and point is drawn?

I think the bounding box and points are purely for illustration purposes here and could be removed, their output is not actually used. The original idea was that they would feed into some algorithm which would compute a watershed shapefile which would then in turn be fed to GSSHA but the intermediate step never materialized.

>What effect does having no elevation grid path have?

Not sure when that would ever occur, it is always set by:

```python
sim.model_creator.elevation_grid_path = get_file_from_quest(sim.model_creator.project_name, sim.elevation_service, 'elevation', sim.model_creator.mask_shapefile)
```

>Does 'INFO:rasterio._base:Failed to auto identify EPSG: 7' indicate anything important?

Not as far as I can tell, it still ends up using the correct CRS.

>Does something need to happen for db_session(Optional[database session]): Active database session object. Required for existing model. and project_manager(Optional[ProjectFile]): Initialized ProjectFile object. Required for existing model.?

Never seen these myself.

>Should we update bokeh, or downgrade numpy, to get rid of .../bokeh/core/json_encoder.py:80: FutureWarning: Conversion of the second argument of issubdtype fromfloattonp.floatingis deprecated.?

Perhaps we should just update to bokeh 0.12.15dev1?

>Do we need to do anything about # TODO: how does the info here relate to that set earlier??

GSSHA Workflow is in a very rudimentary state as we were told to deprioritize it, as such we never really went back and reviewed/improved the parameterization model. Doesn't seem like it's a priority now.

>Which packages are not open source? (Quest?)

Pretty sure quest is open-source now see: https://github.com/erdc/quest/blob/master/LICENSE I'm not entirely sure about the status of the other libraries now.

>It looks like there are three intensities simulated (128, 256, 512), yet the final visualization shows only two (256,512). What happened to 128?

Trying this now, will report back.

>Also, in the last commit here I turned off the bit that aborts when the simulation output directory exists, as it's very confusing and awkward to have to manually find and delete the output each time for the run to succeed when working on the notebook. It seems to work fine, but it's worth double-checking that it's ok.

As long as it's still running, which it seems to be, that seems fine.

**Comment by philippjfr** [comment]
>I can't seem to get any reliable effect from adding points that have assocated values like 100, 1000, or 1000. Is it broken somehow?

Okay I just tried again and there was indeed something off this time. Will have a look at the code now.

**Comment by philippjfr** [comment]
So this is pretty bizarre but I'm now confident it's not our code that's doing it. It seems filigree is ignoring refine points with a size that exceeds a certain value, in the particular example I tried declaring a size of ``5859.53`` seems to work while any value ``>=5859.54`` was simply ignored. It seems this is entirely dependent on the position of the refine point though, I think what happens is that if the refine point position plus the size offset fall outside the bounding box it is ignored.

**Comment by philippjfr** [comment]
>Thanks. I'll open an issue about the ignored points; that's very serious because people are likely to want reduced resolution near the boundaries, and because such points are silently being ignored (or else there's a warning and we aren't seeing it in this context).

Agreed, adding a check that detects whether the point is contained within the bounding box should be straightforward, but someone would have to confirm that my complete guess is correct first. 

>I'm referring to the blank spaces here:

That's just an issue with the parameterization which isn't flexible enough atm, it is set explicitly in code, so I don't think that's anything to worry about.

>This issue seems to be the only remaining showstopper?

I launched that notebook hours ago and it still hasn't completed, did you change anything about it?

**Comment by jbednar** [comment]
It takes about 10 minutes for me, but it does require internet access; maybe there's some issue there for you?

**Comment by philippjfr** [comment]
>It takes about 10 minutes for me, but it does require internet access; maybe there's some issue there for you?

It's definitely running it's just **very** slow, which is always the case for me when it downloads the tifs. The reason why I'm asking whether you changed it, because I'm sure I had it set up that it would only have to download the data for one of the runs and reuse it for the others but it's definitely downloading the data 3 times now.

**Comment by jbednar** [comment]
I just ran it again, and it took 4 minutes on my laptop...

**Comment by jbednar** [comment]
Anyway, no, you can study the diffs, but definitely no intentional changes to how it downloads any data.

**Comment by philippjfr** [comment]
Unfortunately I can't really debug what's going on since it still doesn't want to run in any reasonable time frame for me.

**Comment by jbednar** [comment]
The missing 128 was found; it was a stray bit of code that we'll push to the branch shortly.  I've opened issue #29 about the problem with large points.

**Comment by jbednar** [comment]
Should be ready to merge once the tests pass.

**Pull request merged**
