### PR TITLE
Allow defining path_type and crs on Annotator classes

### PR DESCRIPTION
**Pull request by philippjfr**
Improves the Annotator classes a bit by allowing a user to define:

* path_type: To switch between drawing gv.Polygons and gv.Path types
* crs: Declare the coordinate system for the annotations

### CODE REVIEW

**Comment by philippjfr** [comment]
@kvpevey this should address some of the things you were trying to do in your PR. Instead of defining a completely separate PathAnnotator you can now simply switch from drawing Polygons to Paths by declaring the ``path_type``, e.g. in your notebook you could do: 

```
viz = PolyAndPointAnnotator(path_type=gv.Path, polys=[[189579.0, 338923.0], [189893.0, 339369.0]], points=[188910.28,339661.13], crs=ccrs.UTM(17))
viz.view()
```

**Comment by kcpevey** [comment]
@philippjfr  Does this allow for the poly annotator to be EITHER path or poly? i.e. I cannot have both a path and poly in this visualization - ALL the `self.polys` will/must actually be paths?

**Comment by philippjfr** [comment]
Currently yes, but I suppose we could create a ``PointPolyPathAnnotator``.

**Comment by kcpevey** [comment]
No need for that at this point. Let's wait for generalized annotators before we revisit that idea.

**Comment by philippjfr** [comment]
This is passing now so I'll go ahead and merge.

**Pull request merged**
